export const SET_SPINNER_FALSE = "SET_SPINNER_FALSE"
export const SET_SPINNER_TRUE = "SET_SPINNER_TRUE"

export const SHOW_SNACKBAR = "SHOW_SNACKBAR"
export const HIDE_SNACKBAR = "HIDE_SNACKBAR"

export const GET_TESTCASE_LIST = "GET_TESTCASE_LIST"
export const SET_TESTCASE_LIST = "SET_TESTCASE_LIST"
export const ADD_TESTCASE_TO_LIST = "ADD_TESTCASE_TO_LIST"
export const REMOVE_TESTCASE_FROM_LIST = "REMOVE_TESTCASE_FROM_LIST"

export const GET_TESTSUITE_LIST = "GET_TESTSUITE_LIST"
export const SET_TESTSUITE_LIST = "SET_TESTSUITE_LIST"
export const CREATE_TESTSUITE = "CREATE_TESTSUITE"
export const DELETE_TESTSUITE = "DELETE_TESTSUITE"

